name: multi-currency-account-services

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/bank_account_db
      SPRING_R2DBC_USERNAME: test_user
      SPRING_R2DBC_PASSWORD: test_password
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/bank_account_db
      SPRING_FLYWAY_USER: test_user
      SPRING_FLYWAY_PASSWORD: test_password
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: bank_account_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
