name: multi-currency-account-services

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      spring_flyway_url: jdbc:postgresql://db:5432/bank_account_db
      spring_r2dbc_url: jdbc:postgresql://db:5432/bank_account_db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: bank_account_db
